/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateJournalEntryForm: typeof import('./src/components/CreateJournalEntryForm.vue')['default']
    CreatePaymentEntryForm: typeof import('./src/components/CreatePaymentEntryForm.vue')['default']
    FiltersPanel: typeof import('./src/components/FiltersPanel.vue')['default']
    NumberCard: typeof import('./src/components/NumberCard.vue')['default']
    ReconciliationDialog: typeof import('./src/components/ReconciliationDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionsTable: typeof import('./src/components/TransactionsTable.vue')['default']
    VoucherSelectionTable: typeof import('./src/components/VoucherSelectionTable.vue')['default']
  }
}
